'use strict';
/* ════════════════════════════════════════════════
   TerraBuilder — App Logic
════════════════════════════════════════════════ */

// ── STATE ─────────────────────────────────────
const S = {
  page: 'home',
  provider: 'gcp',       // active cloud provider
  project: '',
  file: null,
  resources: [],
  env: 'prod',
  platform: '',
  promptVersion: 'v1',
};

// ── PROVIDERS ─────────────────────────────────
const PROVIDERS = [
  {
    id: 'gcp',
    label: 'Google Cloud',
    shortLabel: 'GCP',
    color: '#4285F4',
    status: 'active',
    serviceCount: 28,
  },
  {
    id: 'aws',
    label: 'Amazon Web Services',
    shortLabel: 'AWS',
    color: '#FF9900',
    status: 'coming-soon',
    serviceCount: 0,
  },
  {
    id: 'azure',
    label: 'Microsoft Azure',
    shortLabel: 'Azure',
    color: '#0078D4',
    status: 'coming-soon',
    serviceCount: 0,
  },
];

// ── SERVICES ──────────────────────────────────
const GCP_ICONS = 'google-cloud-legacy-icons';
const SERVICES_BY_PROVIDER = {
  gcp: [
    { name: 'Cloud Run', icon: `${GCP_ICONS}/cloud_run/cloud_run.svg` },
    { name: 'Cloud SQL', icon: `${GCP_ICONS}/cloud_sql/cloud_sql.svg` },
    { name: 'BigQuery', icon: `${GCP_ICONS}/bigquery/bigquery.svg` },
    { name: 'Cloud Storage', icon: `${GCP_ICONS}/cloud_storage/cloud_storage.svg` },
    { name: 'Pub/Sub', icon: `${GCP_ICONS}/pubsub/pubsub.svg` },
    { name: 'Cloud Functions', icon: `${GCP_ICONS}/cloud_functions/cloud_functions.svg` },
    { name: 'GKE', icon: `${GCP_ICONS}/google_kubernetes_engine/google_kubernetes_engine.svg` },
    { name: 'Compute Engine', icon: `${GCP_ICONS}/compute_engine/compute_engine.svg` },
    { name: 'Cloud Armor', icon: `${GCP_ICONS}/cloud_armor/cloud_armor.svg` },
    { name: 'VPC', icon: `${GCP_ICONS}/virtual_private_cloud/virtual_private_cloud.svg` },
    { name: 'Cloud NAT', icon: `${GCP_ICONS}/cloud_nat/cloud_nat.svg` },
    { name: 'Load Balancer', icon: `${GCP_ICONS}/cloud_load_balancing/cloud_load_balancing.svg` },
    { name: 'Artifact Registry', icon: `${GCP_ICONS}/artifact_registry/artifact_registry.svg` },
    { name: 'Secret Manager', icon: `${GCP_ICONS}/secret_manager/secret_manager.svg` },
    { name: 'IAM', icon: `${GCP_ICONS}/identity_and_access_management/identity_and_access_management.svg` },
    { name: 'Cloud Build', icon: `${GCP_ICONS}/cloud_build/cloud_build.svg` },
    { name: 'Cloud Spanner', icon: `${GCP_ICONS}/cloud_spanner/cloud_spanner.svg` },
    { name: 'Firestore', icon: `${GCP_ICONS}/firestore/firestore.svg` },
    { name: 'Bigtable', icon: `${GCP_ICONS}/bigtable/bigtable.svg` },
    { name: 'Dataflow', icon: `${GCP_ICONS}/dataflow/dataflow.svg` },
    { name: 'Composer', icon: `${GCP_ICONS}/cloud_composer/cloud_composer.svg` },
    { name: 'Memorystore', icon: `${GCP_ICONS}/memorystore/memorystore.svg` },
    { name: 'Cloud DNS', icon: `${GCP_ICONS}/cloud_dns/cloud_dns.svg` },
    { name: 'Cloud CDN', icon: `${GCP_ICONS}/cloud_cdn/cloud_cdn.svg` },
    { name: 'Cloud Scheduler', icon: `${GCP_ICONS}/cloud_scheduler/cloud_scheduler.svg` },
    { name: 'Cloud Tasks', icon: `${GCP_ICONS}/cloud_tasks/cloud_tasks.svg` },
    { name: 'Vertex AI', icon: `${GCP_ICONS}/vertexai/vertexai.svg` },
    { name: 'Dataproc', icon: `${GCP_ICONS}/dataproc/dataproc.svg` },
  ],
  // ── Populate when AWS support launches ──
  aws: [],
  // ── Populate when Azure support launches ──
  azure: [],
};

// ── EXTRACT LOGS (provider-aware) ─────────────
function getExtractLogs() {
  const p = PROVIDERS.find(p => p.id === S.provider);
  return [
    '> Parsing image metadata…',
    '> Running vision analysis on diagram…',
    `> Identifying ${p ? p.shortLabel : ''} service icons…`,
    '> Mapping connectivity patterns…',
    '> Cross-referencing known architectures…',
    '> Extracting resource nodes…',
    '> Processing relationships…',
    '> Computing environment requirements…',
    '> Finalizing resource list…',
  ];
}

// ── TERRAFORM BOILERPLATE BY PROVIDER ─────────
const GEN_LINES_BY_PROVIDER = {
  gcp: [
    '# Auto-generated by TerraBuilder AI',
    '',
    'terraform {',
    '  required_version = ">= 1.5.0"',
    '  required_providers {',
    '    google = {',
    '      source  = "hashicorp/google"',
    '      version = "~> 5.0"',
    '    }',
    '  }',
    '  backend "gcs" {',
    '    bucket = "tf-state-{PROJECT}"',
    '    prefix = "terraform/state"',
    '  }',
    '}',
    '',
    'provider "google" {',
    '  project = var.project_id',
    '  region  = var.region',
    '}',
  ],
  aws: [
    '# Auto-generated by TerraBuilder AI',
    '',
    'terraform {',
    '  required_version = ">= 1.5.0"',
    '  required_providers {',
    '    aws = {',
    '      source  = "hashicorp/aws"',
    '      version = "~> 5.0"',
    '    }',
    '  }',
    '  backend "s3" {',
    '    bucket = "tf-state-{PROJECT}"',
    '    key    = "terraform/state"',
    '    region = var.region',
    '  }',
    '}',
    '',
    'provider "aws" {',
    '  region = var.region',
    '}',
  ],
  azure: [
    '# Auto-generated by TerraBuilder AI',
    '',
    'terraform {',
    '  required_version = ">= 1.5.0"',
    '  required_providers {',
    '    azurerm = {',
    '      source  = "hashicorp/azurerm"',
    '      version = "~> 3.0"',
    '    }',
    '  }',
    '  backend "azurerm" {',
    '    resource_group_name  = "tf-state-rg"',
    '    storage_account_name = "tfstate{PROJECT}"',
    '    container_name       = "tfstate"',
    '    key                  = "terraform.tfstate"',
    '  }',
    '}',
    '',
    'provider "azurerm" {',
    '  features {}',
    '}',
  ],
};

// ── SET PROVIDER ───────────────────────────────
function setProvider(id) {
  const prov = PROVIDERS.find(p => p.id === id);
  if (!prov) return;

  if (prov.status === 'coming-soon') {
    showToast(`${prov.label} support is coming soon!`, 'ok');
    return;
  }

  S.provider = id;

  // Update provider switcher pills
  document.querySelectorAll('.prov-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.provider === id);
  });

  // Update dynamic text throughout the UI
  const heroProvEl = document.getElementById('heroProviderName');
  if (heroProvEl) heroProvEl.textContent = prov.label;

  const heroBadgeEl = document.getElementById('heroBadge');
  if (heroBadgeEl) heroBadgeEl.textContent = `AI-Powered · ${prov.shortLabel} Infrastructure Generation`;

  const promptsLabelEl = document.getElementById('promptsProviderLabel');
  if (promptsLabelEl) {
    const count = (SERVICES_BY_PROVIDER[id] || []).length;
    promptsLabelEl.textContent = `${count} ${prov.shortLabel} service${count !== 1 ? 's' : ''}`;
  }

  const buildProvEl = document.getElementById('buildProviderBadge');
  if (buildProvEl) {
    buildProvEl.textContent = prov.shortLabel;
    buildProvEl.style.color = prov.color;
  }

  const statsServicesEl = document.getElementById('statServiceCount');
  if (statsServicesEl) {
    const count = (SERVICES_BY_PROVIDER[id] || []).length;
    statsServicesEl.textContent = count || '—';
  }

  // Re-render services grid if on prompts page
  renderServices(document.getElementById('srchInput')?.value || '');
}



const PIPELINE_YAML = {
  github: `name: Terraform CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: \${{ secrets.WIF_PROVIDER }}
          service_account: \${{ secrets.SA_EMAIL }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan`,

  gitlab: `stages:
  - validate
  - plan
  - deploy

variables:
  TF_VERSION: "1.5.0"

.tf_base: &tf_base
  image: hashicorp/terraform:\${TF_VERSION}
  before_script:
    - terraform init

validate:
  <<: *tf_base
  stage: validate
  script:
    - terraform validate
    - terraform fmt -check

plan:
  <<: *tf_base
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths: [tfplan]
    expire_in: 1 day

deploy:
  <<: *tf_base
  stage: deploy
  script:
    - terraform apply -auto-approve tfplan
  environment: production
  only:
    - main`,

  cloudbuild: `timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'hashicorp/terraform:1.5.0'
    id: tf-init
    entrypoint: terraform
    args: ['init']

  - name: 'hashicorp/terraform:1.5.0'
    id: tf-validate
    entrypoint: terraform
    args: ['validate']

  - name: 'hashicorp/terraform:1.5.0'
    id: tf-plan
    entrypoint: terraform
    args: ['plan', '-out=tfplan']

  - name: 'hashicorp/terraform:1.5.0'
    id: tf-apply
    entrypoint: terraform
    args: ['apply', '-auto-approve', 'tfplan']`,

  jenkins: `pipeline {
  agent {
    docker {
      image 'hashicorp/terraform:1.5.0'
      args '--entrypoint='
    }
  }

  environment {
    TF_VAR_project_id = "\${env.GCP_PROJECT_ID}"
  }

  stages {
    stage('Init') {
      steps {
        sh 'terraform init'
      }
    }
    stage('Validate') {
      steps {
        sh 'terraform validate'
        sh 'terraform fmt -check'
      }
    }
    stage('Plan') {
      steps {
        sh 'terraform plan -out=tfplan'
        archiveArtifacts 'tfplan'
      }
    }
    stage('Apply') {
      when { branch 'main' }
      input { message 'Deploy to production?' }
      steps {
        sh 'terraform apply -auto-approve tfplan'
      }
    }
  }

  post {
    always { cleanWs() }
  }
}`,
};

// ── LOGIN ──────────────────────────────────────
function doLogin(e) {
  e.preventDefault();
  const btn = document.getElementById('lbtn');
  btn.disabled = true;
  btn.textContent = 'Signing in…';
  setTimeout(() => {
    document.getElementById('pg-login').style.display = 'none';
    document.getElementById('app').style.display = 'block';
    go('home');
    btn.disabled = false;
    btn.innerHTML = 'Sign In <svg width="14" height="14" fill="none" viewBox="0 0 24 24"><path d="M5 12h14M12 5l7 7-7 7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>';
  }, 700);
}

// ── NAVIGATION ─────────────────────────────────
function go(page) {
  document.querySelectorAll('.pg').forEach(p => p.classList.remove('active'));
  document.querySelectorAll('.nl').forEach(l => l.classList.remove('active'));
  const pg = document.getElementById('pg-' + page);
  const nl = document.getElementById('nl-' + page);
  if (pg) pg.classList.add('active');
  if (nl) nl.classList.add('active');
  S.page = page;
  if (page === 'prompts') renderServices('');
  if (page === 'home') startTerminal();
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

// ── HOME PAGE DROP ─────────────────────────────
function hdOver(e, id) { e.preventDefault(); document.getElementById(id).classList.add('drag'); }
function hdLeave(id) { document.getElementById(id).classList.remove('drag'); }

function hdDrop(e) {
  e.preventDefault();
  hdLeave('homeDrop');
  const f = e.dataTransfer.files[0];
  if (f) { go('build'); setTimeout(() => setFile(f), 200); }
}
function homeFileSelect(e) {
  const f = e.target.files[0];
  if (f) { go('build'); setTimeout(() => setFile(f), 200); }
}

// ── BUILD: PROJECT DROPDOWN ────────────────────
function toggleProjDrop(e) {
  e.stopPropagation();
  const list = document.getElementById('projDropList');
  const open = list.classList.toggle('open');
  if (open) {
    // Close when clicking outside
    setTimeout(() => document.addEventListener('click', closeProjDropOutside, { once: true }), 0);
  }
}

function closeProjDropOutside() {
  document.getElementById('projDropList')?.classList.remove('open');
}

function chooseProjItem(e, val) {
  e.stopPropagation();
  S.project = val;
  const label = document.getElementById('projSelLabel');
  if (label) label.textContent = val || 'Select project…';
  document.getElementById('projDropList')?.classList.remove('open');
}

function openNewProj() {
  document.getElementById('newProjInput').value = '';
  document.getElementById('newProjOverlay').style.display = 'flex';
  setTimeout(() => document.getElementById('newProjInput').focus(), 100);
}
function closeNewProj(e) {
  if (e && e.target !== document.getElementById('newProjOverlay')) return;
  document.getElementById('newProjOverlay').style.display = 'none';
}
function createProj() {
  const v = document.getElementById('newProjInput').value.trim();
  if (!v) { showToast('Enter a project name', 'err'); return; }
  // Add to custom dropdown list
  const list = document.getElementById('projDropList');
  if (list) {
    const item = document.createElement('div');
    item.className = 'pdl-item';
    item.textContent = v;
    item.onclick = (e) => chooseProjItem(e, v);
    list.appendChild(item);
  }
  chooseProjItem({ stopPropagation: () => { } }, v);
  closeNewProj();
  showToast(`Project "${v}" created`, 'ok');
}


// ── BUILD: FILE ────────────────────────────────
function hdDropBuild(e) {
  e.preventDefault();
  hdLeave('stageDrop');
  const f = e.dataTransfer.files[0];
  if (f) setFile(f);
}
function buildFileSelect(e) { const f = e.target.files[0]; if (f) setFile(f); }

function setFile(f) {
  const allowed = ['image/png', 'image/jpeg', 'image/jpg', 'application/pdf'];
  if (!allowed.includes(f.type)) { showToast('PNG, JPG, or PDF only', 'err'); return; }
  if (f.size > 10 * 1024 * 1024) { showToast('File must be under 10MB', 'err'); return; }
  S.file = f;

  const area = document.getElementById('filePreviewArea');
  area.innerHTML = '';
  if (f.type.startsWith('image/')) {
    const r = new FileReader();
    r.onload = ev => { area.innerHTML = `<img src="${ev.target.result}" alt="preview"/>`; };
    r.readAsDataURL(f);
  } else {
    area.innerHTML = `<div style="padding:32px;color:var(--t2);text-align:center">📄 ${f.name}</div>`;
  }
  document.getElementById('fileName').textContent = f.name;
  document.getElementById('fileSize').textContent = (f.size / 1024).toFixed(0) + ' KB';
  document.getElementById('sdContent').style.display = 'none';
  document.getElementById('sdSelected').style.display = 'block';
}

function clearBuildFile() {
  S.file = null;
  document.getElementById('buildFile').value = '';
  document.getElementById('sdContent').style.display = 'block';
  document.getElementById('sdSelected').style.display = 'none';
}

function resetBuild() {
  S.file = null; S.resources = []; S.project = '';
  clearBuildFile();
  showStage('upload');
  setTrail(1);
  document.getElementById('projSel').value = '';
}

// ── BUILD: STAGES ──────────────────────────────
function showStage(name) {
  ['upload', 'extract', 'config', 'generating', 'done'].forEach(s => {
    const el = document.getElementById('stage-' + s);
    if (el) el.style.display = s === name ? 'block' : 'none';
  });
}

function setTrail(step) {
  ['ts1', 'ts2', 'ts3', 'ts4'].forEach((id, i) => {
    const el = document.getElementById(id);
    if (!el) return;
    el.classList.remove('active', 'done');
    if (i + 1 < step) el.classList.add('done');
    else if (i + 1 === step) el.classList.add('active');
  });
}

// ── BUILD: EXTRACTION ──────────────────────────
function runExtraction() {
  if (!S.file) return;
  showStage('extract');
  setTrail(2);
  setNavStatus(true, 'Analyzing…');

  const log = document.getElementById('exLog');
  log.innerHTML = '';
  let i = 0;

  const tick = setInterval(() => {
    if (i < EXTRACT_LOGS.length) {
      const cls = i === EXTRACT_LOGS.length - 1 ? 'hi' : 'log-line';
      log.innerHTML += `<div class="${cls}">${EXTRACT_LOGS[i]}</div>`;
      log.scrollTop = log.scrollHeight;
      i++;
    } else {
      clearInterval(tick);
      document.getElementById('exHeading').textContent = 'Extraction complete!';
      document.getElementById('exSub').textContent = 'Resources identified from your architecture';
      setTimeout(() => showConfigStage(), 700);
    }
  }, 320);
}

function showConfigStage() {
  // Simulate extracted resources
  S.resources = ['cloud-run', 'bigquery', 'cloud-sql', 'cloud-storage', 'pub-sub'];
  renderChips();
  document.getElementById('cvCount').textContent = S.resources.length;
  showStage('config');
  setTrail(3);
  setNavStatus(false);
  // default env
  selectEnv('prod');
}

// ── BUILD: RESOURCES ───────────────────────────
function renderChips() {
  const wrap = document.getElementById('resourceChips');
  wrap.innerHTML = S.resources.map(r => `
    <span class="res-chip">
      ${r}
      <button class="chip-del" onclick="delChip('${r}')" title="Remove">×</button>
    </span>
  `).join('');
  document.getElementById('cvCount').textContent = S.resources.length;
}
function delChip(name) {
  S.resources = S.resources.filter(r => r !== name);
  renderChips();
}
function addResFromInput() {
  const inp = document.getElementById('addResInput');
  const v = inp.value.trim().toLowerCase().replace(/\s+/g, '-');
  if (!v) return;
  if (S.resources.includes(v)) { showToast('Already exists', 'err'); return; }
  S.resources.push(v);
  renderChips();
  inp.value = '';
  inp.focus();
}
function addResKey(e) { if (e.key === 'Enter') addResFromInput(); }

// ── BUILD: ENV ─────────────────────────────────
function selectEnv(env) {
  S.env = env;
  ['dev', 'staging', 'prod'].forEach(e => {
    document.getElementById('ep-' + e).classList.toggle('ep-active', e === env);
  });
}

// ── BUILD: GENERATE ────────────────────────────
function generateTerraform() {
  if (S.resources.length === 0) { showToast('Add at least one resource', 'err'); return; }
  showStage('generating');
  setTrail(4);
  setNavStatus(true, 'Generating…');

  const el = document.getElementById('genCodePreview');
  el.textContent = '';
  let i = 0;

  const lines = [
    ...(GEN_LINES_BY_PROVIDER[S.provider] || GEN_LINES_BY_PROVIDER.gcp),
    '',
    '# ── Resources ──────────────────────────────────',
    ...S.resources.flatMap(r => [
      '',
      `module "${r.replace(/-/g, '_')}" {`,
      `  source    = "./modules/${r}"`,
      `  project   = var.project_id`,
      `  region    = var.region`,
      `  env       = "${S.env}"`,
      `}`,
    ]),
  ];

  const tick = setInterval(() => {
    if (i < lines.length) {
      el.textContent += lines[i] + '\n';
      el.scrollTop = el.scrollHeight;
      i++;
    } else {
      clearInterval(tick);
      setTimeout(showDoneStage, 500);
    }
  }, 55);
}

function showDoneStage() {
  const files = [
    'main.tf', 'variables.tf', 'outputs.tf', 'terraform.tfvars',
    ...S.resources.map(r => `modules/${r}/main.tf`)
  ];
  document.getElementById('doneProjName').textContent = S.project || 'your project';
  document.getElementById('doneFiles').innerHTML = files.map(f =>
    `<div class="done-file">${f}<span>✓ generated</span></div>`
  ).join('');
  showStage('done');
  setNavStatus(false);
  showToast('Terraform generated successfully!', 'ok');
}

function downloadTF() {
  const blob = new Blob(['# TerraBuilder generated terraform\n'], { type: 'application/zip' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `${S.project || 'terraform'}-modules.zip`;
  a.click();
  showToast('Downloaded!', 'ok');
}

// ── NAV STATUS ─────────────────────────────────
function setNavStatus(show, text) {
  const ns = document.getElementById('navStatus');
  if (ns) { ns.style.display = show ? 'flex' : 'none'; }
  const nsText = document.getElementById('nsText');
  if (nsText && text) nsText.textContent = text;
}

// ── PROMPTS ────────────────────────────────────
function renderServices(q) {
  const grid = document.getElementById('servicesGrid');
  const empty = document.getElementById('emptyState');
  const count = document.getElementById('srchCount');
  const query = (q || '').trim().toLowerCase();

  const SERVICES = SERVICES_BY_PROVIDER[S.provider] || [];
  const filtered = query ? SERVICES.filter(s => s.name.toLowerCase().includes(query)) : SERVICES;

  document.getElementById('emptyQ') && (document.getElementById('emptyQ').textContent = query);
  if (filtered.length === 0) {
    grid.innerHTML = '';
    empty.style.display = 'flex';
    count.textContent = '0 services';
  } else {
    empty.style.display = 'none';
    count.textContent = filtered.length + ' service' + (filtered.length !== 1 ? 's' : '');
    grid.innerHTML = filtered.map(s => `
      <div class="svc-card">
        <div class="svc-top">
          <div class="svc-ico">
            <img src="${s.icon}" alt="${s.name}" width="32" height="32"
              onerror="this.style.display='none';this.nextElementSibling.style.display='flex'" />
            <span class="svc-ico-fallback" style="display:none">☁️</span>
          </div>
          <div class="svc-name">${s.name}</div>
        </div>
        <div class="svc-btns">
          <button class="svc-dl1" onclick="dlPrompt('${s.name}','v1')">V1 Basic</button>
          <button class="svc-dl2" onclick="dlPrompt('${s.name}','v2')">V2 Module</button>
        </div>
      </div>
    `).join('');
  }
}

function filterSvcs() {
  const v = document.getElementById('srchInput').value;
  const clr = document.getElementById('srchClear');
  if (clr) clr.style.display = v ? 'inline' : 'none';
  renderServices(v);
}

function clearSrch() {
  document.getElementById('srchInput').value = '';
  const clr = document.getElementById('srchClear'); if (clr) clr.style.display = 'none';
  renderServices('');
}

function setVersion(v) {
  S.promptVersion = v;
  ['v1', 'v2'].forEach(x => {
    document.getElementById('vt-' + x).classList.toggle('active', x === v);
  });
  const viText = document.getElementById('viText');
  if (viText) {
    viText.textContent = v === 'v1'
      ? 'V1 — Single resource block, static values, great for quick snippets'
      : 'V2 — Reusable module pattern with variables, outputs, and remote state';
  }
  renderServices(document.getElementById('srchInput').value || '');
}

function dlPrompt(svc, ver) {
  const content = ver === 'v1'
    ? `# TerraBuilder — ${svc} V1 Basic Prompt\n\nGenerate a single Terraform resource block for ${svc} on GCP.\nInclude all required parameters, use static values for development.\n`
    : `# TerraBuilder — ${svc} V2 Modular Prompt\n\nGenerate a production-ready Terraform module for ${svc} on GCP.\nInclude: variables.tf, outputs.tf, main.tf, README.md\nSupport for dev/staging/prod environments with conditional resources.\n`;
  const blob = new Blob([content], { type: 'text/plain' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `${svc.replace(/\s+/g, '-').toLowerCase()}-${ver}.txt`;
  a.click();
  showToast(`${svc} ${ver.toUpperCase()} downloaded`, 'ok');
}

// ── CI/CD ──────────────────────────────────────
function selectPlat(plat) {
  S.platform = plat;
  document.querySelectorAll('.plat-tile').forEach(t => t.classList.remove('selected'));
  const tile = document.getElementById('pt-' + plat);
  if (tile) tile.classList.add('selected');

  const panel = document.getElementById('cicdPanel');
  const empty = document.getElementById('cicdEmpty');
  panel.style.display = 'grid';
  empty.style.display = 'none';

  const names = { github: 'GitHub Actions', gitlab: 'GitLab CI', cloudbuild: 'Cloud Build', jenkins: 'Jenkins' };
  document.getElementById('cpTitle').textContent = names[plat] || plat;

  // Full repo-relative file paths
  const fullPaths = {
    github: '.github/workflows/terraform.yml',
    gitlab: '.gitlab-ci.yml',
    cloudbuild: 'cloudbuild.yaml',
    jenkins: 'Jenkinsfile',
  };
  const fullPath = fullPaths[plat] || 'pipeline.yml';
  const parts = fullPath.split('/');
  const shortName = parts[parts.length - 1];

  // VS Code tab — show just the filename
  const tabName = document.getElementById('yamlFileName');
  if (tabName) tabName.textContent = shortName;

  // Breadcrumb — show full path with › separators
  const crumb = document.getElementById('ypBreadcrumb');
  if (crumb) {
    const SEP = `<span style="color:#444;margin:0 3px">›</span>`;
    crumb.innerHTML = parts.map((seg, i) => {
      const isLast = i === parts.length - 1;
      return `<span style="color:${isLast ? '#ccc' : '#666'}">${seg}</span>`;
    }).join(SEP);
  }

  // Status bar platform label
  const ypPlatStatus = document.getElementById('ypPlatformStatus');
  if (ypPlatStatus) ypPlatStatus.textContent = names[plat] || plat;

  liveUpdateYaml();
}


function copyYaml() {
  const el = document.getElementById('yamlContent');
  if (!el) return;
  const yaml = el.innerText || el.textContent;
  if (!yaml) return;
  navigator.clipboard.writeText(yaml).then(() => showToast('Copied to clipboard!', 'ok'));
}

function downloadPipeline() {
  if (!S.platform) { showToast('Select a platform first', 'err'); return; }
  const el = document.getElementById('yamlContent');
  const yaml = el ? (el.innerText || el.textContent) : '';
  const fnames = { github: 'terraform.yml', gitlab: '.gitlab-ci.yml', cloudbuild: 'cloudbuild.yaml', jenkins: 'Jenkinsfile' };
  const blob = new Blob([yaml], { type: 'text/yaml' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = fnames[S.platform] || 'pipeline.yml';
  a.click();
  showToast(`${S.platform} pipeline downloaded!`, 'ok');
}

// ── THEME TOGGLE ───────────────────────────────
function toggleTheme() {
  const isDark = document.documentElement.getAttribute('data-theme') !== 'light';
  const next = isDark ? 'light' : 'dark';
  if (next === 'light') {
    document.documentElement.setAttribute('data-theme', 'light');
  } else {
    document.documentElement.removeAttribute('data-theme');
  }
  localStorage.setItem('tb-theme', next);
}

// Restore saved theme on load
(function applyTheme() {
  const saved = localStorage.getItem('tb-theme');
  if (saved === 'light') document.documentElement.setAttribute('data-theme', 'light');
})();

// ── YAML SYNTAX HIGHLIGHTER ───────────────────
function highlightYaml(text) {
  // Escape HTML first
  const esc = s => s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  return text.split('\n').map(raw => {
    const line = esc(raw);

    // Comment lines
    if (/^\s*#/.test(raw)) return `<span class="yc">${line}</span>`;

    // YAML document separator ---
    if (/^---/.test(raw)) return `<span class="yd">${line}</span>`;

    // Key: value lines
    const kvMatch = raw.match(/^(\s*)([\w\-\.]+)(\s*:\s*)(.*)$/);
    if (kvMatch) {
      const [, indent, key, colon, rest] = kvMatch;
      const escapedIndent = esc(indent);
      const escapedKey = esc(key);
      const escapedColon = esc(colon);

      let coloredVal = '';
      if (!rest.trim()) {
        coloredVal = '';
      } else if (/^\s*\|/.test(rest) || /^\s*>/.test(rest)) {
        coloredVal = `<span class="yv">${esc(rest)}</span>`;
      } else if (/^\s*(true|false|yes|no|on|off)\s*$/i.test(rest)) {
        coloredVal = `<span class="yb">${esc(rest)}</span>`;
      } else if (/^\s*[\d.]+\s*$/.test(rest)) {
        coloredVal = `<span class="yn">${esc(rest)}</span>`;
      } else if (/^\s*["']/.test(rest)) {
        coloredVal = `<span class="yv">${esc(rest)}</span>`;
      } else if (/^\s*\$\{/.test(rest) || /^\s*\$\{\{/.test(rest)) {
        // Template vars — keep gold
        coloredVal = `<span class="ye">${esc(rest)}</span>`;
      } else {
        coloredVal = `<span class="yv">${esc(rest)}</span>`;
      }

      return `${escapedIndent}<span class="yk">${escapedKey}</span><span style="color:#d4d4d4">${escapedColon}</span>${coloredVal}`;
    }

    // List items  - value
    const listMatch = raw.match(/^(\s*)(- )(.*)$/);
    if (listMatch) {
      const [, indent, dash, rest] = listMatch;
      return `${esc(indent)}<span style="color:#d4d4d4">${esc(dash)}</span><span class="yv">${esc(rest)}</span>`;
    }

    return line;
  }).join('\n');
}

// ── LIVE YAML PREVIEW ──────────────────────────
function liveUpdateYaml() {
  if (!S.platform) return;
  const branch = (document.getElementById('branchInput')?.value || 'main').trim();
  const tfVer = (document.getElementById('tfVersion')?.value || '1.5.0').trim();
  const pushOn = document.getElementById('pushTrig')?.checked ?? true;
  const prOn = document.getElementById('prTrig')?.checked ?? true;
  const envDev = document.getElementById('envDev')?.checked ?? true;
  const envStg = document.getElementById('envStaging')?.checked ?? true;
  const envProd = document.getElementById('envProd')?.checked ?? false;
  const dm = document.querySelector('input[name="dm"]:checked')?.value || 'progressive';

  const envList = [envDev && 'development', envStg && 'staging', envProd && 'production'].filter(Boolean);
  const applyCondition = dm === 'auto'
    ? ''
    : dm === 'manual'
      ? `      if: github.event_name == 'workflow_dispatch'\n`
      : `      if: github.ref == 'refs/heads/${branch}'\n`;

  let yaml = '';

  if (S.platform === 'github') {
    const onBlock = [];
    if (pushOn) onBlock.push(`  push:\n    branches: [${branch}]`);
    if (prOn) onBlock.push(`  pull_request:\n    branches: [${branch}]`);
    if (dm === 'manual') onBlock.push(`  workflow_dispatch: {}`);
    yaml = `name: Terraform CI/CD
on:
${onBlock.join('\n')}

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    environment: ${envList.join(', ') || 'development'}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: \${{ secrets.WIF_PROVIDER }}
          service_account: \${{ secrets.SA_EMAIL }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${tfVer}"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
${applyCondition || `        if: github.ref == 'refs/heads/${branch}'\n`}        run: terraform apply -auto-approve tfplan`;
  }

  else if (S.platform === 'gitlab') {
    const stages = envList.map(e => `  - ${e}`).join('\n') || '  - plan';
    yaml = `stages:\n${stages}\n\nvariables:\n  TF_VERSION: "${tfVer}"\n\n`;
    yaml += `.tf_base: &tf_base\n  image: hashicorp/terraform:\${TF_VERSION}\n  before_script:\n    - terraform init\n\n`;
    if (pushOn) yaml += `only: [${branch}]\n`;
    yaml += envList.map(e => `${e}:\n  <<: *tf_base\n  stage: ${e}\n  script:\n    - terraform plan\n    - terraform apply -auto-approve\n`).join('\n');
  }

  else if (S.platform === 'cloudbuild') {
    yaml = `timeout: '1800s'\noptions:\n  logging: CLOUD_LOGGING_ONLY\n\nsteps:\n`;
    yaml += `  - name: 'hashicorp/terraform:${tfVer}'\n    id: tf-init\n    entrypoint: terraform\n    args: ['init']\n\n`;
    yaml += `  - name: 'hashicorp/terraform:${tfVer}'\n    id: tf-validate\n    entrypoint: terraform\n    args: ['validate']\n\n`;
    yaml += `  - name: 'hashicorp/terraform:${tfVer}'\n    id: tf-plan\n    entrypoint: terraform\n    args: ['plan', '-out=tfplan']\n\n`;
    if (dm !== 'manual') {
      yaml += `  - name: 'hashicorp/terraform:${tfVer}'\n    id: tf-apply\n    entrypoint: terraform\n    args: ['apply', '-auto-approve', 'tfplan']\n`;
    }
    if (envList.length) yaml += `\nsubstitutions:\n  _ENV: ${envList[envList.length - 1]}`;
  }

  else if (S.platform === 'jenkins') {
    const applyStage = dm === 'manual'
      ? `    stage('Apply') {\n      input { message 'Deploy?' }\n      steps { sh 'terraform apply -auto-approve tfplan' }\n    }`
      : `    stage('Apply') {\n      when { branch '${branch}' }\n      steps { sh 'terraform apply -auto-approve tfplan' }\n    }`;
    yaml = `pipeline {\n  agent any\n  environment {\n    TF_VERSION = '${tfVer}'\n    ENVIRONMENTS = '${envList.join(',')}' \n  }\n  stages {\n    stage('Init') { steps { sh 'terraform init' } }\n    stage('Validate') { steps { sh 'terraform validate' } }\n    stage('Plan') {\n      steps {\n        sh 'terraform plan -out=tfplan'\n        archiveArtifacts 'tfplan'\n      }\n    }\n${applyStage}\n  }\n  post { always { cleanWs() } }\n}`;
  }

  // Apply syntax-highlighted content
  const codeEl = document.getElementById('yamlContent');
  if (codeEl) codeEl.innerHTML = highlightYaml(yaml);

  // Update gutter line numbers
  const gutter = document.getElementById('ypGutter');
  if (gutter) {
    const lineCount = yaml.split('\n').length;
    gutter.innerHTML = Array.from({ length: lineCount }, (_, i) => i + 1).join('\n');
  }

  // Update status bar
  const lineCountEl = document.getElementById('ypLineCount');
  if (lineCountEl) lineCountEl.textContent = `${yaml.split('\n').length} lines`;

  // Sync gutter scroll with code scroll
  if (codeEl && gutter && !codeEl._gutterSynced) {
    codeEl._gutterSynced = true;
    codeEl.addEventListener('scroll', () => { gutter.scrollTop = codeEl.scrollTop; });
  }
}


// ── TOAST ──────────────────────────────────────
let _toastT;
function showToast(msg, type) {
  const t = document.getElementById('toast');
  t.textContent = msg;
  t.className = 'show' + (type ? ' ' + type : '');
  clearTimeout(_toastT);
  _toastT = setTimeout(() => { t.className = ''; }, 3000);
}

// ── INIT ────────────────────────────────────────
(function init() {
  document.getElementById('pg-login').style.display = 'flex';
  document.getElementById('app').style.display = 'none';
  showStage('upload');
})();

// ── TERMINAL ANIMATION ─────────────────────────
const TERM_SCRIPT = [
  { cls: 'tl-prompt', t: '❯ ' }, { cls: 'tl-cmd', t: 'terrabuilder analyze diagram.png', pause: 600 },
  { cls: 'tl-out', t: '  Initializing AI vision model…', pause: 200 },
  { cls: 'tl-out', t: '  Parsing architecture nodes…', pause: 180 },
  { cls: 'tl-res', t: '  ✓ Found 6 GCP resources', pause: 300 },
  { cls: 'tl-out', t: '', pause: 80 },
  { cls: 'tl-file', t: '  cloud-run        → extracted', pause: 60 },
  { cls: 'tl-file', t: '  bigquery         → extracted', pause: 60 },
  { cls: 'tl-file', t: '  cloud-sql        → extracted', pause: 60 },
  { cls: 'tl-file', t: '  cloud-storage    → extracted', pause: 60 },
  { cls: 'tl-file', t: '  pub-sub          → extracted', pause: 60 },
  { cls: 'tl-file', t: '  cloud-armor      → extracted', pause: 300 },
  { cls: 'tl-out', t: '', pause: 80 },
  { cls: 'tl-prompt', t: '❯ ' }, { cls: 'tl-cmd', t: 'terrabuilder generate --env=prod', pause: 700 },
  { cls: 'tl-res', t: '  ✓ main.tf', pause: 90 },
  { cls: 'tl-res', t: '  ✓ variables.tf', pause: 90 },
  { cls: 'tl-res', t: '  ✓ outputs.tf', pause: 90 },
  { cls: 'tl-res', t: '  ✓ modules/cloud-run/main.tf', pause: 90 },
  { cls: 'tl-res', t: '  ✓ modules/bigquery/main.tf', pause: 90 },
  { cls: 'tl-res', t: '  ✓ modules/cloud-sql/main.tf', pause: 200 },
  { cls: 'tl-out', t: '', pause: 80 },
  { cls: 'tl-res', t: '  Terraform ready   3.8s total', pause: 2000 },
];

let _termTimer = null;
function startTerminal() {
  const body = document.getElementById('termBody');
  if (!body) return;
  body.innerHTML = '';
  clearTimeout(_termTimer);
  let i = 0;
  let currentLine = null;

  function step() {
    if (i >= TERM_SCRIPT.length) {
      // Restart after a delay
      _termTimer = setTimeout(startTerminal, 3000);
      return;
    }
    const entry = TERM_SCRIPT[i++];
    if (entry.cls === 'tl-prompt') {
      // Start new line with prompt + next word
      const nextEntry = TERM_SCRIPT[i] || {};
      currentLine = document.createElement('div');
      currentLine.className = 'term-line';
      const promptSpan = document.createElement('span');
      promptSpan.className = 'tl-prompt';
      promptSpan.textContent = entry.t;
      currentLine.appendChild(promptSpan);
      const cmdSpan = document.createElement('span');
      cmdSpan.className = 'tl-cmd';
      currentLine.appendChild(cmdSpan);
      body.appendChild(currentLine);
      // Typewrite the next entry (cmd)
      let j = 0;
      const cmd = nextEntry.t || '';
      i++; // skip the cmd entry
      function type() {
        if (j < cmd.length) {
          cmdSpan.textContent += cmd[j++];
          _termTimer = setTimeout(type, 35);
        } else {
          _termTimer = setTimeout(step, nextEntry.pause || 200);
        }
      }
      _termTimer = setTimeout(type, 60);
    } else {
      const line = document.createElement('div');
      line.className = 'term-line';
      const span = document.createElement('span');
      span.className = entry.cls;
      span.textContent = entry.t;
      line.appendChild(span);
      body.appendChild(line);
      body.scrollTop = body.scrollHeight;
      _termTimer = setTimeout(step, entry.pause || 120);
    }
  }
  step();
}
